//! Ephemeral Gradle init script: force re-resolve of SNAPSHOT / changing modules.
//!
//! Used on cascade **consumer** builds (and **B** rebuild steps) so a just-published
//! Nexus SNAPSHOT is picked up without a full `--refresh-dependencies`.

use std::fs;
use std::path::{Path, PathBuf};

use crate::error::{AppError, AppResult};

/// Filename under `<config_dir>/cache/`.
pub const SNAPSHOT_INIT_SCRIPT_NAME: &str = "force-latest-snapshots.gradle";

/// Groovy init script body (Gradle init scripts are always Groovy).
///
/// Sets `cacheChangingModulesFor 0` on every configuration so Maven SNAPSHOTs
/// recheck the repository on each resolve instead of the default ~24h cache.
const SNAPSHOT_INIT_SCRIPT: &str = r#"// Generated by tako — do not edit by hand.
// Re-resolve changing modules (Maven SNAPSHOTs) on every build.
gradle.beforeProject { project ->
    project.configurations.configureEach { configuration ->
        configuration.resolutionStrategy.cacheChangingModulesFor(0, 'seconds')
    }
}
"#;

/// Ensure the snapshot init script exists under `config_dir/cache/` and return its path.
///
/// Writes (or rewrites) the file so upgrades pick up script content changes.
pub fn ensure_snapshot_init_script(config_dir: &Path) -> AppResult<PathBuf> {
    let cache = config_dir.join("cache");
    fs::create_dir_all(&cache).map_err(|e| {
        AppError::Config(format!(
            "create cache dir {}: {e}",
            cache.display()
        ))
    })?;
    let path = cache.join(SNAPSHOT_INIT_SCRIPT_NAME);
    // Always rewrite so content stays in sync with this binary.
    fs::write(&path, SNAPSHOT_INIT_SCRIPT).map_err(|e| {
        AppError::Config(format!("write init script {}: {e}", path.display()))
    })?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn writes_init_script_under_cache() {
        let dir = env::temp_dir().join(format!(
            "tako-init-script-test-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let path = ensure_snapshot_init_script(&dir).expect("write");
        assert!(path.ends_with("cache/force-latest-snapshots.gradle") || path.ends_with("cache\\force-latest-snapshots.gradle"));
        let body = fs::read_to_string(&path).unwrap();
        assert!(body.contains("cacheChangingModulesFor"));
        assert!(body.contains("beforeProject"));
        let _ = fs::remove_dir_all(&dir);
    }
}
